import streamlit as st
import pickle
import numpy as np
import pandas as pd
import shap
import matplotlib.pyplot as plt
from components.gauge_chart import show_gauge
from components.plain_text import show_text_confidence
from components.feature_mapping import decode_case, FEATURE_LABELS


def run_dashboard(condition: str):
    """Run the credit risk dashboard with a fixed visualization condition.

    Args:
        condition: either "gauge" or "text" — fixed for this app instance.
    """

    st.set_page_config(
        page_title="Credit Risk Dashboard",
        layout="wide",
        initial_sidebar_state="collapsed"
    )

    st.markdown("""
        <style>
            div[data-testid="stVerticalBlockBorderWrapper"] {
                height: 100%;
                min-height: 400px;
            }
        </style>
    """, unsafe_allow_html=True)

    # ── Load Model & Data ─────────────────────────────────────────
    @st.cache_resource
    @st.cache_resource
    def load_model():
        with open("model/rf_model.pkl", "rb") as f:
            rf = pickle.load(f)
        with open("model/X_test.pkl", "rb") as f:
            X_test = pickle.load(f)
        with open("model/y_test.pkl", "rb") as f:
            y_test = pickle.load(f)
        explainer = shap.TreeExplainer(rf)
        return rf, explainer, X_test, y_test

    rf, explainer, X_test, y_test = load_model()

    # ── Session State ─────────────────────────────────────────────
    if "case_idx" not in st.session_state:
        st.session_state.case_idx = 0

    # ── Current Case ──────────────────────────────────────────────
    idx = st.session_state.case_idx
    case = X_test.iloc[idx]
    proba = rf.predict_proba(case.values.reshape(1, -1))[0]
    pred = np.argmax(proba)
    confidence = proba[pred]
    pred_label = "Low Risk" if pred == 0 else "High Risk"

    # ── Header ────────────────────────────────────────────────────
    st.title("Credit Risk Dashboard")
    st.caption(
        "This dashboard presents individual credit risk predictions generated by a "
        "Random Forest classifier trained on the German Credit Dataset (Hofmann, 1994). "
        "Each prediction is accompanied by a SHAP-based local explanation and an "
        "uncertainty visualization showing the model's confidence."
    )
    st.markdown("---")

    # ── Applicant Box ─────────────────────────────────────────────
    with st.container(border=True):
        nav1, nav2, nav3 = st.columns([4, 1, 1])
        with nav1:
            st.markdown(f"### Applicant {idx + 1} of {len(X_test)}")
        with nav2:
            if st.button("← Previous", use_container_width=True):
                st.session_state.case_idx = max(0, st.session_state.case_idx - 1)
        with nav3:
            if st.button("Next →", use_container_width=True):
                st.session_state.case_idx = min(len(X_test) - 1, st.session_state.case_idx + 1)

        st.markdown("---")

        decoded = decode_case(case)
        sections = {
            "Financial": [
                "Checking Account", "Savings Account", "Credit History",
                "Credit Amount (DM)", "Other Installments",
                "Existing Credits", "Installment Rate (%)"
            ],
            "Personal": [
                "Age (years)", "Personal Status", "Employment",
                "Job", "Liable People", "Telephone",
                "Foreign Worker", "Residence Since (years)"
            ],
            "Loan": [
                "Duration (months)", "Purpose", "Other Debtors",
                "Property", "Housing"
            ]
        }

        sec_cols = st.columns(3)
        for col, (section_name, features) in zip(sec_cols, sections.items()):
            with col:
                st.markdown(f"**{section_name}**")
                for feat in features:
                    if feat in decoded:
                        st.markdown(
                            f"<span style='color:#4A90D9; font-size:13px;'>{feat}:</span> "
                            f"<span style='font-size:13px;'>{decoded[feat]}</span>",
                            unsafe_allow_html=True
                        )

    st.markdown("---")

    # ── Prediction + Confidence ───────────────────────────────────
    pred_col, conf_col = st.columns([1, 2])

    with pred_col:
        with st.container(border=True):
            st.subheader("Model Prediction")
            st.markdown(f"## {pred_label}")
            st.caption(
                "The model predicts whether this applicant represents a "
                "low or high credit risk based on the features above."
            )

    with conf_col:
        with st.container(border=True):
            st.subheader("Model Confidence")
            st.caption(
                "The confidence score shows how certain the model is about this "
                "prediction. A higher value means the model is more sure that its "
                "assessment is correct."
            )

            # Fixed condition
            if condition == "gauge":
                fig = show_gauge(confidence)
                st.plotly_chart(fig, use_container_width=True)
            else:
                show_text_confidence(confidence)

    st.markdown("---")

    # ── SHAP Explanation ──────────────────────────────────────────
    st.subheader("Prediction Explanation (SHAP)")
    st.caption(
        "The chart below shows which features had the most impact on this prediction. "
        "Red bars push the prediction towards the predicted class; "
        "blue bars push against it."
    )

    readable_feature_names = [FEATURE_LABELS.get(f, f) for f in X_test.columns]

    shap_values = explainer.shap_values(case.values.reshape(1, -1))
    fig, ax = plt.subplots(figsize=(14, 3))
    shap.bar_plot(
        shap_values[0, :, pred],
        feature_names=readable_feature_names,
        max_display=10,
        show=False
    )
    st.pyplot(fig)
    plt.close()